name: Generate Portfolio

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at 00:00 UTC

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run portfolio generator
        run: |
          pip install requests
          python scripts/generate_portfolio.py pboric

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./portfolio.md
          git commit -m "Update portfolio page [auto]" || echo "No changes to commit"
          git push
